In [4]:
import pandas as pd

In [45]:
df = pd.read_csv('/Users/psw/Desktop/Dataset_-_Dataset.csv')

In [64]:
product_date_df = pd.DataFrame(columns=['Product', 'Country', 'Variety', 'Grades', 'Region', 'Product_Date', 'Product_Quantity'])

super_keys = ['Product', 'Country', 'Variety', 'Grades', 'Region']

info_table = df[super_keys]

product_table, region_table = info_table[['Product', 'Variety', 'Grades', 'Region']].drop_duplicates(), info_table[['Region', 'Country']].drop_duplicates()

In [64]:
product_table.head(10)

,Product,Variety,Grades,Region
0,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Second Quality,"Pedro Aguirre Cerda, Santiago"
1,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Second Quality,"La Calera, Quillota"
2,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Second Quality,Araucania
3,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / First Quality,Araucania
4,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / First Quality,"La Calera, Quillota"
5,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / First Quality,"Pedro Aguirre Cerda, Santiago"
6,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Special Quality,"Pedro Aguirre Cerda, Santiago"
7,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Third Quality,"La Calera, Quillota"
8,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Special Quality,Araucania
9,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Third Quality,"Pedro Aguirre Cerda, Santiago"

In [65]:
region_table.head(10)

                           Region Country
0   Pedro Aguirre Cerda, Santiago   Chile
1             La Calera, Quillota   Chile
2                       Araucania   Chile
10                Coquimbo, Elqui   Chile
13                   Puerto Montt   Chile
15             Chillán, Diguillín   Chile
17                       Santiago   Chile
21                          Talca   Chile
24                     Concepción   Chile
45                 Ovalle, Limari   Chile

In [66]:
    
melt_df = df.melt(id_vars=['Product', 'Country', 'Variety', 'Grades', 'Region'], var_name='Produce_Date', value_name='Product_Quantity').drop(columns=['Country'])

date_quantity_df = melt_df[melt_df['Product_Quantity'].notna()]
date_quantity_df.head(10)

,Product,Variety,Grades,Region,Produce_Date,Product_Quantity
0,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Second Quality,"Pedro Aguirre Cerda, Santiago",2020-11-16,4.15
1,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Second Quality,"La Calera, Quillota",2020-11-16,5.05
2,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Second Quality,Araucania,2020-11-16,5.35
3,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / First Quality,Araucania,2020-11-16,5.67
4,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / First Quality,"La Calera, Quillota",2020-11-16,4.81
5,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / First Quality,"Pedro Aguirre Cerda, Santiago",2020-11-16,4.90
6,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Special Quality,"Pedro Aguirre Cerda, Santiago",2020-11-16,5.08
7,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Third Quality,"La Calera, Quillota",2020-11-16,3.68
8,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Special Quality,Araucania,2020-11-16,5.62
9,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Third Quality,"Pedro Aguirre Cerda, Santiago",2020-11-16,3.81
10,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Special Quality,"Coquimbo, Elqui",2020-11-16,5.34
11,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / First Quality,"Coquimbo, Elqui",2020-11-16,4.10
12,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Second Quality,"Coquimbo, Elqui",2020-11-16,4.47
13,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / First Quality,Puerto Montt,2020-11-16,5.92
14,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Second Quality,Puerto Montt,2020-11-16,5.58
15,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Second Quality,"Chillán, Diguillín",2020-11-16,4.46
16,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / First Quality,"Chillán, Diguillín",2020-11-16,5.42
21,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / First Quality,Talca,2020-11-16,4.91
22,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Second Quality,Talca,2020-11-16,4.77
23,Avocado (#99),Avocado / Variety / Hass,Avocado / Grade / Special Quality,Talca,2020-11-16,5.61